        -:    0:Source:/home/florin/FMI/SEM2/SDA/Lab4/DictionarLDI/Iterator.cpp
        -:    0:Graph:/home/florin/FMI/SEM2/SDA/Lab4/DictionarLDI/cmake-build-debug-coverage/CMakeFiles/DictionarLDI.dir/Iterator.cpp.gcno
        -:    0:Data:/home/florin/FMI/SEM2/SDA/Lab4/DictionarLDI/cmake-build-debug-coverage/CMakeFiles/DictionarLDI.dir/Iterator.cpp.gcda
        -:    0:Runs:1
        -:    1:#include <exception>
        -:    2:#include "Iterator.h"
        -:    3:#include "DO.h"
        -:    4:
        -:    5:using namespace std;
        -:    6:
function _ZN8IteratorC2ERK2DO called 33 returned 100% blocks executed 100%
       33:    7:Iterator::Iterator(const DO& d) : dict(d){
        -:    8:	/* de adaugat */
       33:    9:    this->curent = dict.prim;
       33:   10:}
        -:   11:
function _ZN8Iterator4primEv called 34 returned 100% blocks executed 100%
       34:   12:void Iterator::prim(){
        -:   13:	/* de adaugat */
       34:   14:    this->curent = dict.prim;
       34:   15:}
        -:   16:
function _ZN8Iterator7urmatorEv called 13130 returned 100% blocks executed 50%
    13130:   17:void Iterator::urmator(){
        -:   18:	/* de adaugat */
    13130:   19:    if (!valid())
    13130:   19-block  0
call    0 returned 13130
branch  1 taken 0 (fallthrough)
branch  2 taken 13130
    #####:   20:        throw exception();
    %%%%%:   20-block  0
call    0 never executed
call    1 never executed
call    2 never executed
    13130:   21:    this->curent = dict.urm[this->curent];
    13130:   22:}
        -:   23:
function _ZNK8Iterator5validEv called 33639 returned 100% blocks executed 100%
    33639:   24:bool Iterator::valid() const{
        -:   25:	/* de adaugat */
    33639:   26:	return this->curent != -1;
    33639:   26-block  0
        -:   27:}
        -:   28:
function _ZNK8Iterator7elementEv called 13339 returned 100% blocks executed 57%
    13339:   29:TElem Iterator::element() const{
        -:   30:	/* de adaugat */
    13339:   31:    if(!valid())
    13339:   31-block  0
call    0 returned 13339
branch  1 taken 0 (fallthrough)
branch  2 taken 13339
    #####:   32:        throw exception();
    %%%%%:   32-block  0
call    0 never executed
call    1 never executed
call    2 never executed
    13339:   33:	return dict.e[curent];
    13339:   33-block  0
        -:   34:}
        -:   35:
        -:   36:
